### ISSUE TITLE
Is there a problem with two event handlers?

### ISSUE THREAD

**Issue by markotom** [mrjoelkemp/jquery.bum-smack#12]
Your jQuery plugin is great, for sure! I agree with your motivation to use infinite scroll with Backbone Collection and the Irish's plugin is not very helpful in this case. But, I realized that I cannot have two event handlers assigned to the same selector and I think it's a problem if someone wants to manage different event handlers in different collections. For instance:

``` js
$(window).smack()
  .done(function () {
    console.log('Bottom');
  });

$(window).smack()
  .done(function () {
    console.log('Bottom Twice?');
  });
```

The first promise seems overridden. Yes, I can use `then` to execute both anonymous functions, but I lack modularity. I don't know if is an error or decided by design. Thanks in advance!

**Comment by mrjoelkemp** [comment]
Hey @markotom thanks for the kind words and for filing the issue. That's an interesting use case that wasn't planned for but should have worked. A quick workaround for this is to use pub/sub and trigger an event from the first callback; however, that's not ideal. I'll investigate and follow up.

**Comment by mrjoelkemp** [comment]
Sorry for the delay in this. I started looking into it but this required some drastic changes in the library – as it was originally built for only a single smack binding at a time. I opted to keep things as is until there were more requests for allowing multiple smack bindings.

I'll close this for now since there's a pub/sub workaround that isn't too bad. Thanks again for filing the issue.
