### ISSUE TITLE
Support for reaching top of the element

### ISSUE THREAD

**Issue by pawel-piskorz** [mrjoelkemp/jquery.bum-smack#2]
Follow up on discussion here:
https://github.com/pawel-piskorz/jquery.bum-smack/commit/a7eff5dc86780ce4681509f3445ab993ef118349

**Summary:**
_What?_
It would be nice to have smack detect when user reaches top of the element too.

_How?_
Optional attribute "edge" with values "top"/"bottom" ("bottom is default value").

_Drawbacks_
This will keep backward compatibility, but requires to change of smack scroll event namespace.

**Comment by mrjoelkemp** [comment]
Still thinking about this. Leaning toward an `edge` parameter that supports the following values: 'top', 'bottom' (default), or 'either'.
- If 'either' is supplied as the `edge`, then smack resolves with 'top' or 'bottom'.
- Otherwise, smack just simply resolves when the edge specified (or defaulted) is smacked.

With this proposition, I'm not so certain the event namespace needs to be modified. Any thoughts?

Let me know if you have time to whip up a PR or if you want me to take a stab at it. 

FYI, I just added some tooling to this lib since I was unhappy with mechanical, visual testing. There's now a Mocha test-suite and grunt build process with some instructions in the readme.

**Comment by pawel-piskorz** [comment]
You're right, with "either" option namespace won't have to change, but user won't be able to use different threshold for top and bottom.
We could skip changing namespace by storing smack options on the element, I'll try to make a PR for you after the xmass.
